name: Tests

on: 
  pull_request:
    branches: [ master ]
jobs:
  common-tests:
    name: "Common tests"
    runs-on: ubuntu-latest
    strategy:
     matrix:
      projDir: [test/NextApi.Client.Tests, test/NextApi.Server.EfCore.Tests]
    container: "mcr.microsoft.com/dotnet/core/sdk:3.1"
    steps:
    - uses: actions/checkout@v2
    - name: Restoring packages...
      working-directory: ${{ matrix.projDir }}
      run: dotnet restore -v q
    - name: Building project...
      working-directory: ${{ matrix.projDir }}
      run: dotnet build -c Debug -v q --no-restore
    - name: Testing...
      working-directory: ${{ matrix.projDir }}
      run: dotnet test -v n --no-restore --no-build

  integration-tests-mysql:
    name: "Integration tests / MySQL"
    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: test/NextApi.Server.Tests
    steps:
    - uses: actions/checkout@v2
    - name: Running tests...
      run: docker-compose -f docker-compose-mysql-tests.yml up --exit-code-from=tests
  integration-tests-mariadb:
    name: "Integration tests / MariaDB"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test/NextApi.Server.Tests
    steps:
      - uses: actions/checkout@v2
      - name: Running tests...
        run: docker-compose -f docker-compose-mariadb-tests.yml up --exit-code-from=tests

